// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: other/amor_var/language.proto

package amor_var

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_en  Language = 0
	Language_fil Language = 1
	Language_ceb Language = 2
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "en",
		1: "fil",
		2: "ceb",
	}
	Language_value = map[string]int32{
		"en":  0,
		"fil": 1,
		"ceb": 2,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_other_amor_var_language_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_other_amor_var_language_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_other_amor_var_language_proto_rawDescGZIP(), []int{0}
}

var File_other_amor_var_language_proto protoreflect.FileDescriptor

var file_other_amor_var_language_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x61, 0x6d, 0x6f, 0x72, 0x5f, 0x76, 0x61, 0x72,
	0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x6d, 0x6f, 0x72, 0x76, 0x61, 0x72, 0x2a, 0x24, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x66, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x65, 0x62, 0x10, 0x02, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x69, 0x6e,
	0x6f, 0x6c, 0x69, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x2f, 0x61, 0x6d, 0x6f, 0x72, 0x5f, 0x76, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_other_amor_var_language_proto_rawDescOnce sync.Once
	file_other_amor_var_language_proto_rawDescData []byte
)

func file_other_amor_var_language_proto_rawDescGZIP() []byte {
	file_other_amor_var_language_proto_rawDescOnce.Do(func() {
		file_other_amor_var_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_other_amor_var_language_proto_rawDesc), len(file_other_amor_var_language_proto_rawDesc)))
	})
	return file_other_amor_var_language_proto_rawDescData
}

var file_other_amor_var_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_other_amor_var_language_proto_goTypes = []any{
	(Language)(0), // 0: amorvar.Language
}
var file_other_amor_var_language_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_other_amor_var_language_proto_init() }
func file_other_amor_var_language_proto_init() {
	if File_other_amor_var_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_other_amor_var_language_proto_rawDesc), len(file_other_amor_var_language_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_other_amor_var_language_proto_goTypes,
		DependencyIndexes: file_other_amor_var_language_proto_depIdxs,
		EnumInfos:         file_other_amor_var_language_proto_enumTypes,
	}.Build()
	File_other_amor_var_language_proto = out.File
	file_other_amor_var_language_proto_goTypes = nil
	file_other_amor_var_language_proto_depIdxs = nil
}
