// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: amornotification/amornotification.proto

package amornotification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmorNotification_GetRealTimeNotifications_FullMethodName = "/projectamor_api.amornotification.v1.AmorNotification/GetRealTimeNotifications"
)

// AmorNotificationClient is the client API for AmorNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmorNotificationClient interface {
	GetRealTimeNotifications(ctx context.Context, in *GetRealTimeNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRealTimeNotificationsResponse], error)
}

type amorNotificationClient struct {
	cc grpc.ClientConnInterface
}

func NewAmorNotificationClient(cc grpc.ClientConnInterface) AmorNotificationClient {
	return &amorNotificationClient{cc}
}

func (c *amorNotificationClient) GetRealTimeNotifications(ctx context.Context, in *GetRealTimeNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRealTimeNotificationsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AmorNotification_ServiceDesc.Streams[0], AmorNotification_GetRealTimeNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRealTimeNotificationsRequest, GetRealTimeNotificationsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AmorNotification_GetRealTimeNotificationsClient = grpc.ServerStreamingClient[GetRealTimeNotificationsResponse]

// AmorNotificationServer is the server API for AmorNotification service.
// All implementations must embed UnimplementedAmorNotificationServer
// for forward compatibility.
type AmorNotificationServer interface {
	GetRealTimeNotifications(*GetRealTimeNotificationsRequest, grpc.ServerStreamingServer[GetRealTimeNotificationsResponse]) error
	mustEmbedUnimplementedAmorNotificationServer()
}

// UnimplementedAmorNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmorNotificationServer struct{}

func (UnimplementedAmorNotificationServer) GetRealTimeNotifications(*GetRealTimeNotificationsRequest, grpc.ServerStreamingServer[GetRealTimeNotificationsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetRealTimeNotifications not implemented")
}
func (UnimplementedAmorNotificationServer) mustEmbedUnimplementedAmorNotificationServer() {}
func (UnimplementedAmorNotificationServer) testEmbeddedByValue()                          {}

// UnsafeAmorNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmorNotificationServer will
// result in compilation errors.
type UnsafeAmorNotificationServer interface {
	mustEmbedUnimplementedAmorNotificationServer()
}

func RegisterAmorNotificationServer(s grpc.ServiceRegistrar, srv AmorNotificationServer) {
	// If the following call pancis, it indicates UnimplementedAmorNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmorNotification_ServiceDesc, srv)
}

func _AmorNotification_GetRealTimeNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRealTimeNotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AmorNotificationServer).GetRealTimeNotifications(m, &grpc.GenericServerStream[GetRealTimeNotificationsRequest, GetRealTimeNotificationsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AmorNotification_GetRealTimeNotificationsServer = grpc.ServerStreamingServer[GetRealTimeNotificationsResponse]

// AmorNotification_ServiceDesc is the grpc.ServiceDesc for AmorNotification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmorNotification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectamor_api.amornotification.v1.AmorNotification",
	HandlerType: (*AmorNotificationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRealTimeNotifications",
			Handler:       _AmorNotification_GetRealTimeNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "amornotification/amornotification.proto",
}
